// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awolmsg.proto

#ifndef PROTOBUF_awolmsg_2eproto__INCLUDED
#define PROTOBUF_awolmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace awolmsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_awolmsg_2eproto();
void protobuf_AssignDesc_awolmsg_2eproto();
void protobuf_ShutdownFile_awolmsg_2eproto();

class MsgAgent;
class MsgExt;
class MsgFlag;
class MsgStoreCallBack;
class MsgMysqlStoreTable;
class Msg;
class Msg_MsgData;

enum MaxMsgTypeConstValue {
  MAX_MSG_TYPE_NUM = 64
};
bool MaxMsgTypeConstValue_IsValid(int value);
const MaxMsgTypeConstValue MaxMsgTypeConstValue_MIN = MAX_MSG_TYPE_NUM;
const MaxMsgTypeConstValue MaxMsgTypeConstValue_MAX = MAX_MSG_TYPE_NUM;
const int MaxMsgTypeConstValue_ARRAYSIZE = MaxMsgTypeConstValue_MAX + 1;

const ::google::protobuf::EnumDescriptor* MaxMsgTypeConstValue_descriptor();
inline const ::std::string& MaxMsgTypeConstValue_Name(MaxMsgTypeConstValue value) {
  return ::google::protobuf::internal::NameOfEnum(
    MaxMsgTypeConstValue_descriptor(), value);
}
inline bool MaxMsgTypeConstValue_Parse(
    const ::std::string& name, MaxMsgTypeConstValue* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MaxMsgTypeConstValue>(
    MaxMsgTypeConstValue_descriptor(), name, value);
}
enum MsgFlagOwnType {
  MSG_OPT_OWN_BO = 0,
  MSG_OPT_OWN_SO = 1,
  MSG_OPT_OWN_CO = 2
};
bool MsgFlagOwnType_IsValid(int value);
const MsgFlagOwnType MsgFlagOwnType_MIN = MSG_OPT_OWN_BO;
const MsgFlagOwnType MsgFlagOwnType_MAX = MSG_OPT_OWN_CO;
const int MsgFlagOwnType_ARRAYSIZE = MsgFlagOwnType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgFlagOwnType_descriptor();
inline const ::std::string& MsgFlagOwnType_Name(MsgFlagOwnType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgFlagOwnType_descriptor(), value);
}
inline bool MsgFlagOwnType_Parse(
    const ::std::string& name, MsgFlagOwnType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgFlagOwnType>(
    MsgFlagOwnType_descriptor(), name, value);
}
enum MsgFalgStoreOptions {
  MSG_OPT_STORE_NONE = 0,
  MSG_OPT_STORE_TTL = 1,
  MSG_OPT_STORE_SHIFT = 2,
  MSG_OPT_STORE_MYSQL = 4
};
bool MsgFalgStoreOptions_IsValid(int value);
const MsgFalgStoreOptions MsgFalgStoreOptions_MIN = MSG_OPT_STORE_NONE;
const MsgFalgStoreOptions MsgFalgStoreOptions_MAX = MSG_OPT_STORE_MYSQL;
const int MsgFalgStoreOptions_ARRAYSIZE = MsgFalgStoreOptions_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgFalgStoreOptions_descriptor();
inline const ::std::string& MsgFalgStoreOptions_Name(MsgFalgStoreOptions value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgFalgStoreOptions_descriptor(), value);
}
inline bool MsgFalgStoreOptions_Parse(
    const ::std::string& name, MsgFalgStoreOptions* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgFalgStoreOptions>(
    MsgFalgStoreOptions_descriptor(), name, value);
}
enum MsgFalgCpermOptions {
  MSG_OPT_CPERM_NONE = 0,
  MSG_OPT_CPERM_SEND = 1,
  MSG_OPT_CPERM_REMOVE = 2,
  MSG_OPT_CPERM_LIST = 4,
  MSG_OPT_CPERM_UPDATE = 8,
  MSG_OPT_CPERM_ALL = 15
};
bool MsgFalgCpermOptions_IsValid(int value);
const MsgFalgCpermOptions MsgFalgCpermOptions_MIN = MSG_OPT_CPERM_NONE;
const MsgFalgCpermOptions MsgFalgCpermOptions_MAX = MSG_OPT_CPERM_ALL;
const int MsgFalgCpermOptions_ARRAYSIZE = MsgFalgCpermOptions_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgFalgCpermOptions_descriptor();
inline const ::std::string& MsgFalgCpermOptions_Name(MsgFalgCpermOptions value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgFalgCpermOptions_descriptor(), value);
}
inline bool MsgFalgCpermOptions_Parse(
    const ::std::string& name, MsgFalgCpermOptions* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgFalgCpermOptions>(
    MsgFalgCpermOptions_descriptor(), name, value);
}
enum MsgOP {
  MSG_OP_LIST = 1,
  MSG_OP_SET = 2,
  MSG_OP_GET = 3,
  MSG_OP_RM = 4,
  MSG_OP_INSERT = 5
};
bool MsgOP_IsValid(int value);
const MsgOP MsgOP_MIN = MSG_OP_LIST;
const MsgOP MsgOP_MAX = MSG_OP_INSERT;
const int MsgOP_ARRAYSIZE = MsgOP_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgOP_descriptor();
inline const ::std::string& MsgOP_Name(MsgOP value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgOP_descriptor(), value);
}
inline bool MsgOP_Parse(
    const ::std::string& name, MsgOP* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgOP>(
    MsgOP_descriptor(), name, value);
}
// ===================================================================

class MsgAgent : public ::google::protobuf::Message {
 public:
  MsgAgent();
  virtual ~MsgAgent();

  MsgAgent(const MsgAgent& from);

  inline MsgAgent& operator=(const MsgAgent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgAgent& default_instance();

  void Swap(MsgAgent* other);

  // implements Message ----------------------------------------------

  MsgAgent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgAgent& from);
  void MergeFrom(const MsgAgent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional uint64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgAgent)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgAgent* default_instance_;
};
// -------------------------------------------------------------------

class MsgExt : public ::google::protobuf::Message {
 public:
  MsgExt();
  virtual ~MsgExt();

  MsgExt(const MsgExt& from);

  inline MsgExt& operator=(const MsgExt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgExt& default_instance();

  void Swap(MsgExt* other);

  // implements Message ----------------------------------------------

  MsgExt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgExt& from);
  void MergeFrom(const MsgExt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);

  // optional uint32 ttl = 2;
  inline bool has_ttl() const;
  inline void clear_ttl();
  static const int kTtlFieldNumber = 2;
  inline ::google::protobuf::uint32 ttl() const;
  inline void set_ttl(::google::protobuf::uint32 value);

  // optional .awolmsg.MsgAgent from = 3;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 3;
  inline const ::awolmsg::MsgAgent& from() const;
  inline ::awolmsg::MsgAgent* mutable_from();
  inline ::awolmsg::MsgAgent* release_from();
  inline void set_allocated_from(::awolmsg::MsgAgent* from);

  // optional uint32 version = 4;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 4;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgExt)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_ttl();
  inline void clear_has_ttl();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 time_;
  ::google::protobuf::uint32 ttl_;
  ::awolmsg::MsgAgent* from_;
  ::google::protobuf::uint32 version_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgExt* default_instance_;
};
// -------------------------------------------------------------------

class MsgFlag : public ::google::protobuf::Message {
 public:
  MsgFlag();
  virtual ~MsgFlag();

  MsgFlag(const MsgFlag& from);

  inline MsgFlag& operator=(const MsgFlag& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgFlag& default_instance();

  void Swap(MsgFlag* other);

  // implements Message ----------------------------------------------

  MsgFlag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgFlag& from);
  void MergeFrom(const MsgFlag& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .awolmsg.MsgFlagOwnType owner = 1;
  inline bool has_owner() const;
  inline void clear_owner();
  static const int kOwnerFieldNumber = 1;
  inline ::awolmsg::MsgFlagOwnType owner() const;
  inline void set_owner(::awolmsg::MsgFlagOwnType value);

  // optional uint32 store = 2;
  inline bool has_store() const;
  inline void clear_store();
  static const int kStoreFieldNumber = 2;
  inline ::google::protobuf::uint32 store() const;
  inline void set_store(::google::protobuf::uint32 value);

  // optional uint32 cperm = 3;
  inline bool has_cperm() const;
  inline void clear_cperm();
  static const int kCpermFieldNumber = 3;
  inline ::google::protobuf::uint32 cperm() const;
  inline void set_cperm(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgFlag)
 private:
  inline void set_has_owner();
  inline void clear_has_owner();
  inline void set_has_store();
  inline void clear_has_store();
  inline void set_has_cperm();
  inline void clear_has_cperm();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int owner_;
  ::google::protobuf::uint32 store_;
  ::google::protobuf::uint32 cperm_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgFlag* default_instance_;
};
// -------------------------------------------------------------------

class MsgStoreCallBack : public ::google::protobuf::Message {
 public:
  MsgStoreCallBack();
  virtual ~MsgStoreCallBack();

  MsgStoreCallBack(const MsgStoreCallBack& from);

  inline MsgStoreCallBack& operator=(const MsgStoreCallBack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgStoreCallBack& default_instance();

  void Swap(MsgStoreCallBack* other);

  // implements Message ----------------------------------------------

  MsgStoreCallBack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgStoreCallBack& from);
  void MergeFrom(const MsgStoreCallBack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 cookie = 1;
  inline bool has_cookie() const;
  inline void clear_cookie();
  static const int kCookieFieldNumber = 1;
  inline ::google::protobuf::uint64 cookie() const;
  inline void set_cookie(::google::protobuf::uint64 value);

  // optional int32 clientid = 2;
  inline bool has_clientid() const;
  inline void clear_clientid();
  static const int kClientidFieldNumber = 2;
  inline ::google::protobuf::int32 clientid() const;
  inline void set_clientid(::google::protobuf::int32 value);

  // optional .awolmsg.Msg msg = 3;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 3;
  inline const ::awolmsg::Msg& msg() const;
  inline ::awolmsg::Msg* mutable_msg();
  inline ::awolmsg::Msg* release_msg();
  inline void set_allocated_msg(::awolmsg::Msg* msg);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgStoreCallBack)
 private:
  inline void set_has_cookie();
  inline void clear_has_cookie();
  inline void set_has_clientid();
  inline void clear_has_clientid();
  inline void set_has_msg();
  inline void clear_has_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 cookie_;
  ::awolmsg::Msg* msg_;
  ::google::protobuf::int32 clientid_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgStoreCallBack* default_instance_;
};
// -------------------------------------------------------------------

class MsgMysqlStoreTable : public ::google::protobuf::Message {
 public:
  MsgMysqlStoreTable();
  virtual ~MsgMysqlStoreTable();

  MsgMysqlStoreTable(const MsgMysqlStoreTable& from);

  inline MsgMysqlStoreTable& operator=(const MsgMysqlStoreTable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgMysqlStoreTable& default_instance();

  void Swap(MsgMysqlStoreTable* other);

  // implements Message ----------------------------------------------

  MsgMysqlStoreTable* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgMysqlStoreTable& from);
  void MergeFrom(const MsgMysqlStoreTable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional string actor = 2;
  inline bool has_actor() const;
  inline void clear_actor();
  static const int kActorFieldNumber = 2;
  inline const ::std::string& actor() const;
  inline void set_actor(const ::std::string& value);
  inline void set_actor(const char* value);
  inline void set_actor(const char* value, size_t size);
  inline ::std::string* mutable_actor();
  inline ::std::string* release_actor();
  inline void set_allocated_actor(::std::string* actor);

  // optional uint64 msgid = 3;
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 3;
  inline ::google::protobuf::uint64 msgid() const;
  inline void set_msgid(::google::protobuf::uint64 value);

  // optional bytes msg = 4;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 4;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const void* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // optional uint32 version = 5;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 5;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgMysqlStoreTable)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_actor();
  inline void clear_has_actor();
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* actor_;
  ::google::protobuf::uint64 msgid_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 version_;
  ::std::string* msg_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgMysqlStoreTable* default_instance_;
};
// -------------------------------------------------------------------

class Msg_MsgData : public ::google::protobuf::Message {
 public:
  Msg_MsgData();
  virtual ~Msg_MsgData();

  Msg_MsgData(const Msg_MsgData& from);

  inline Msg_MsgData& operator=(const Msg_MsgData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_MsgData& default_instance();

  void Swap(Msg_MsgData* other);

  // implements Message ----------------------------------------------

  Msg_MsgData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_MsgData& from);
  void MergeFrom(const Msg_MsgData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional .awolmsg.MsgExt ext = 3;
  inline bool has_ext() const;
  inline void clear_ext();
  static const int kExtFieldNumber = 3;
  inline const ::awolmsg::MsgExt& ext() const;
  inline ::awolmsg::MsgExt* mutable_ext();
  inline ::awolmsg::MsgExt* release_ext();
  inline void set_allocated_ext(::awolmsg::MsgExt* ext);

  // @@protoc_insertion_point(class_scope:awolmsg.Msg.MsgData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_ext();
  inline void clear_has_ext();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::std::string* data_;
  ::awolmsg::MsgExt* ext_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static Msg_MsgData* default_instance_;
};
// -------------------------------------------------------------------

class Msg : public ::google::protobuf::Message {
 public:
  Msg();
  virtual ~Msg();

  Msg(const Msg& from);

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg& default_instance();

  void Swap(Msg* other);

  // implements Message ----------------------------------------------

  Msg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg& from);
  void MergeFrom(const Msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Msg_MsgData MsgData;

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional .awolmsg.MsgAgent actor = 2;
  inline bool has_actor() const;
  inline void clear_actor();
  static const int kActorFieldNumber = 2;
  inline const ::awolmsg::MsgAgent& actor() const;
  inline ::awolmsg::MsgAgent* mutable_actor();
  inline ::awolmsg::MsgAgent* release_actor();
  inline void set_allocated_actor(::awolmsg::MsgAgent* actor);

  // repeated .awolmsg.Msg.MsgData data = 3;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::awolmsg::Msg_MsgData& data(int index) const;
  inline ::awolmsg::Msg_MsgData* mutable_data(int index);
  inline ::awolmsg::Msg_MsgData* add_data();
  inline const ::google::protobuf::RepeatedPtrField< ::awolmsg::Msg_MsgData >&
      data() const;
  inline ::google::protobuf::RepeatedPtrField< ::awolmsg::Msg_MsgData >*
      mutable_data();

  // optional .awolmsg.MsgFlag flag = 4;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 4;
  inline const ::awolmsg::MsgFlag& flag() const;
  inline ::awolmsg::MsgFlag* mutable_flag();
  inline ::awolmsg::MsgFlag* release_flag();
  inline void set_allocated_flag(::awolmsg::MsgFlag* flag);

  // optional .awolmsg.MsgOP op = 5;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 5;
  inline ::awolmsg::MsgOP op() const;
  inline void set_op(::awolmsg::MsgOP value);

  // @@protoc_insertion_point(class_scope:awolmsg.Msg)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_actor();
  inline void clear_has_actor();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_op();
  inline void clear_has_op();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::awolmsg::MsgAgent* actor_;
  ::google::protobuf::RepeatedPtrField< ::awolmsg::Msg_MsgData > data_;
  ::google::protobuf::int32 type_;
  int op_;
  ::awolmsg::MsgFlag* flag_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static Msg* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgAgent

// required int32 type = 1;
inline bool MsgAgent::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgAgent::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgAgent::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgAgent::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 MsgAgent::type() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgAgent.type)
  return type_;
}
inline void MsgAgent::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgAgent.type)
}

// optional uint64 id = 2;
inline bool MsgAgent::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgAgent::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgAgent::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgAgent::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 MsgAgent::id() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgAgent.id)
  return id_;
}
inline void MsgAgent::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgAgent.id)
}

// -------------------------------------------------------------------

// MsgExt

// optional uint32 time = 1;
inline bool MsgExt::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgExt::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgExt::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgExt::clear_time() {
  time_ = 0u;
  clear_has_time();
}
inline ::google::protobuf::uint32 MsgExt::time() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.time)
  return time_;
}
inline void MsgExt::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgExt.time)
}

// optional uint32 ttl = 2;
inline bool MsgExt::has_ttl() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgExt::set_has_ttl() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgExt::clear_has_ttl() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgExt::clear_ttl() {
  ttl_ = 0u;
  clear_has_ttl();
}
inline ::google::protobuf::uint32 MsgExt::ttl() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.ttl)
  return ttl_;
}
inline void MsgExt::set_ttl(::google::protobuf::uint32 value) {
  set_has_ttl();
  ttl_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgExt.ttl)
}

// optional .awolmsg.MsgAgent from = 3;
inline bool MsgExt::has_from() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgExt::set_has_from() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgExt::clear_has_from() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgExt::clear_from() {
  if (from_ != NULL) from_->::awolmsg::MsgAgent::Clear();
  clear_has_from();
}
inline const ::awolmsg::MsgAgent& MsgExt::from() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.from)
  return from_ != NULL ? *from_ : *default_instance_->from_;
}
inline ::awolmsg::MsgAgent* MsgExt::mutable_from() {
  set_has_from();
  if (from_ == NULL) from_ = new ::awolmsg::MsgAgent;
  // @@protoc_insertion_point(field_mutable:awolmsg.MsgExt.from)
  return from_;
}
inline ::awolmsg::MsgAgent* MsgExt::release_from() {
  clear_has_from();
  ::awolmsg::MsgAgent* temp = from_;
  from_ = NULL;
  return temp;
}
inline void MsgExt::set_allocated_from(::awolmsg::MsgAgent* from) {
  delete from_;
  from_ = from;
  if (from) {
    set_has_from();
  } else {
    clear_has_from();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.MsgExt.from)
}

// optional uint32 version = 4;
inline bool MsgExt::has_version() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgExt::set_has_version() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgExt::clear_has_version() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgExt::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 MsgExt::version() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.version)
  return version_;
}
inline void MsgExt::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgExt.version)
}

// -------------------------------------------------------------------

// MsgFlag

// optional .awolmsg.MsgFlagOwnType owner = 1;
inline bool MsgFlag::has_owner() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgFlag::set_has_owner() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgFlag::clear_has_owner() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgFlag::clear_owner() {
  owner_ = 0;
  clear_has_owner();
}
inline ::awolmsg::MsgFlagOwnType MsgFlag::owner() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgFlag.owner)
  return static_cast< ::awolmsg::MsgFlagOwnType >(owner_);
}
inline void MsgFlag::set_owner(::awolmsg::MsgFlagOwnType value) {
  assert(::awolmsg::MsgFlagOwnType_IsValid(value));
  set_has_owner();
  owner_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgFlag.owner)
}

// optional uint32 store = 2;
inline bool MsgFlag::has_store() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgFlag::set_has_store() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgFlag::clear_has_store() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgFlag::clear_store() {
  store_ = 0u;
  clear_has_store();
}
inline ::google::protobuf::uint32 MsgFlag::store() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgFlag.store)
  return store_;
}
inline void MsgFlag::set_store(::google::protobuf::uint32 value) {
  set_has_store();
  store_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgFlag.store)
}

// optional uint32 cperm = 3;
inline bool MsgFlag::has_cperm() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgFlag::set_has_cperm() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgFlag::clear_has_cperm() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgFlag::clear_cperm() {
  cperm_ = 0u;
  clear_has_cperm();
}
inline ::google::protobuf::uint32 MsgFlag::cperm() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgFlag.cperm)
  return cperm_;
}
inline void MsgFlag::set_cperm(::google::protobuf::uint32 value) {
  set_has_cperm();
  cperm_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgFlag.cperm)
}

// -------------------------------------------------------------------

// MsgStoreCallBack

// optional uint64 cookie = 1;
inline bool MsgStoreCallBack::has_cookie() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgStoreCallBack::set_has_cookie() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgStoreCallBack::clear_has_cookie() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgStoreCallBack::clear_cookie() {
  cookie_ = GOOGLE_ULONGLONG(0);
  clear_has_cookie();
}
inline ::google::protobuf::uint64 MsgStoreCallBack::cookie() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgStoreCallBack.cookie)
  return cookie_;
}
inline void MsgStoreCallBack::set_cookie(::google::protobuf::uint64 value) {
  set_has_cookie();
  cookie_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgStoreCallBack.cookie)
}

// optional int32 clientid = 2;
inline bool MsgStoreCallBack::has_clientid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgStoreCallBack::set_has_clientid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgStoreCallBack::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgStoreCallBack::clear_clientid() {
  clientid_ = 0;
  clear_has_clientid();
}
inline ::google::protobuf::int32 MsgStoreCallBack::clientid() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgStoreCallBack.clientid)
  return clientid_;
}
inline void MsgStoreCallBack::set_clientid(::google::protobuf::int32 value) {
  set_has_clientid();
  clientid_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgStoreCallBack.clientid)
}

// optional .awolmsg.Msg msg = 3;
inline bool MsgStoreCallBack::has_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgStoreCallBack::set_has_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgStoreCallBack::clear_has_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgStoreCallBack::clear_msg() {
  if (msg_ != NULL) msg_->::awolmsg::Msg::Clear();
  clear_has_msg();
}
inline const ::awolmsg::Msg& MsgStoreCallBack::msg() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgStoreCallBack.msg)
  return msg_ != NULL ? *msg_ : *default_instance_->msg_;
}
inline ::awolmsg::Msg* MsgStoreCallBack::mutable_msg() {
  set_has_msg();
  if (msg_ == NULL) msg_ = new ::awolmsg::Msg;
  // @@protoc_insertion_point(field_mutable:awolmsg.MsgStoreCallBack.msg)
  return msg_;
}
inline ::awolmsg::Msg* MsgStoreCallBack::release_msg() {
  clear_has_msg();
  ::awolmsg::Msg* temp = msg_;
  msg_ = NULL;
  return temp;
}
inline void MsgStoreCallBack::set_allocated_msg(::awolmsg::Msg* msg) {
  delete msg_;
  msg_ = msg;
  if (msg) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.MsgStoreCallBack.msg)
}

// -------------------------------------------------------------------

// MsgMysqlStoreTable

// optional uint32 type = 1;
inline bool MsgMysqlStoreTable::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgMysqlStoreTable::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgMysqlStoreTable::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgMysqlStoreTable::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 MsgMysqlStoreTable::type() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgMysqlStoreTable.type)
  return type_;
}
inline void MsgMysqlStoreTable::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgMysqlStoreTable.type)
}

// optional string actor = 2;
inline bool MsgMysqlStoreTable::has_actor() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgMysqlStoreTable::set_has_actor() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgMysqlStoreTable::clear_has_actor() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgMysqlStoreTable::clear_actor() {
  if (actor_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    actor_->clear();
  }
  clear_has_actor();
}
inline const ::std::string& MsgMysqlStoreTable::actor() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgMysqlStoreTable.actor)
  return *actor_;
}
inline void MsgMysqlStoreTable::set_actor(const ::std::string& value) {
  set_has_actor();
  if (actor_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    actor_ = new ::std::string;
  }
  actor_->assign(value);
  // @@protoc_insertion_point(field_set:awolmsg.MsgMysqlStoreTable.actor)
}
inline void MsgMysqlStoreTable::set_actor(const char* value) {
  set_has_actor();
  if (actor_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    actor_ = new ::std::string;
  }
  actor_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolmsg.MsgMysqlStoreTable.actor)
}
inline void MsgMysqlStoreTable::set_actor(const char* value, size_t size) {
  set_has_actor();
  if (actor_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    actor_ = new ::std::string;
  }
  actor_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolmsg.MsgMysqlStoreTable.actor)
}
inline ::std::string* MsgMysqlStoreTable::mutable_actor() {
  set_has_actor();
  if (actor_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    actor_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolmsg.MsgMysqlStoreTable.actor)
  return actor_;
}
inline ::std::string* MsgMysqlStoreTable::release_actor() {
  clear_has_actor();
  if (actor_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = actor_;
    actor_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MsgMysqlStoreTable::set_allocated_actor(::std::string* actor) {
  if (actor_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete actor_;
  }
  if (actor) {
    set_has_actor();
    actor_ = actor;
  } else {
    clear_has_actor();
    actor_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.MsgMysqlStoreTable.actor)
}

// optional uint64 msgid = 3;
inline bool MsgMysqlStoreTable::has_msgid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgMysqlStoreTable::set_has_msgid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgMysqlStoreTable::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgMysqlStoreTable::clear_msgid() {
  msgid_ = GOOGLE_ULONGLONG(0);
  clear_has_msgid();
}
inline ::google::protobuf::uint64 MsgMysqlStoreTable::msgid() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgMysqlStoreTable.msgid)
  return msgid_;
}
inline void MsgMysqlStoreTable::set_msgid(::google::protobuf::uint64 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgMysqlStoreTable.msgid)
}

// optional bytes msg = 4;
inline bool MsgMysqlStoreTable::has_msg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgMysqlStoreTable::set_has_msg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgMysqlStoreTable::clear_has_msg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgMysqlStoreTable::clear_msg() {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& MsgMysqlStoreTable::msg() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgMysqlStoreTable.msg)
  return *msg_;
}
inline void MsgMysqlStoreTable::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set:awolmsg.MsgMysqlStoreTable.msg)
}
inline void MsgMysqlStoreTable::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolmsg.MsgMysqlStoreTable.msg)
}
inline void MsgMysqlStoreTable::set_msg(const void* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolmsg.MsgMysqlStoreTable.msg)
}
inline ::std::string* MsgMysqlStoreTable::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolmsg.MsgMysqlStoreTable.msg)
  return msg_;
}
inline ::std::string* MsgMysqlStoreTable::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MsgMysqlStoreTable::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.MsgMysqlStoreTable.msg)
}

// optional uint32 version = 5;
inline bool MsgMysqlStoreTable::has_version() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgMysqlStoreTable::set_has_version() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgMysqlStoreTable::clear_has_version() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgMysqlStoreTable::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 MsgMysqlStoreTable::version() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgMysqlStoreTable.version)
  return version_;
}
inline void MsgMysqlStoreTable::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgMysqlStoreTable.version)
}

// -------------------------------------------------------------------

// Msg_MsgData

// required uint64 id = 1;
inline bool Msg_MsgData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg_MsgData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg_MsgData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg_MsgData::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Msg_MsgData::id() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.MsgData.id)
  return id_;
}
inline void Msg_MsgData::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.Msg.MsgData.id)
}

// optional bytes data = 2;
inline bool Msg_MsgData::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg_MsgData::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg_MsgData::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg_MsgData::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Msg_MsgData::data() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.MsgData.data)
  return *data_;
}
inline void Msg_MsgData::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolmsg.Msg.MsgData.data)
}
inline void Msg_MsgData::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolmsg.Msg.MsgData.data)
}
inline void Msg_MsgData::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolmsg.Msg.MsgData.data)
}
inline ::std::string* Msg_MsgData::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.MsgData.data)
  return data_;
}
inline ::std::string* Msg_MsgData::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Msg_MsgData::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.MsgData.data)
}

// optional .awolmsg.MsgExt ext = 3;
inline bool Msg_MsgData::has_ext() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Msg_MsgData::set_has_ext() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Msg_MsgData::clear_has_ext() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Msg_MsgData::clear_ext() {
  if (ext_ != NULL) ext_->::awolmsg::MsgExt::Clear();
  clear_has_ext();
}
inline const ::awolmsg::MsgExt& Msg_MsgData::ext() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.MsgData.ext)
  return ext_ != NULL ? *ext_ : *default_instance_->ext_;
}
inline ::awolmsg::MsgExt* Msg_MsgData::mutable_ext() {
  set_has_ext();
  if (ext_ == NULL) ext_ = new ::awolmsg::MsgExt;
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.MsgData.ext)
  return ext_;
}
inline ::awolmsg::MsgExt* Msg_MsgData::release_ext() {
  clear_has_ext();
  ::awolmsg::MsgExt* temp = ext_;
  ext_ = NULL;
  return temp;
}
inline void Msg_MsgData::set_allocated_ext(::awolmsg::MsgExt* ext) {
  delete ext_;
  ext_ = ext;
  if (ext) {
    set_has_ext();
  } else {
    clear_has_ext();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.MsgData.ext)
}

// -------------------------------------------------------------------

// Msg

// required int32 type = 1;
inline bool Msg::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Msg::type() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.type)
  return type_;
}
inline void Msg::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.Msg.type)
}

// optional .awolmsg.MsgAgent actor = 2;
inline bool Msg::has_actor() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg::set_has_actor() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg::clear_has_actor() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg::clear_actor() {
  if (actor_ != NULL) actor_->::awolmsg::MsgAgent::Clear();
  clear_has_actor();
}
inline const ::awolmsg::MsgAgent& Msg::actor() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.actor)
  return actor_ != NULL ? *actor_ : *default_instance_->actor_;
}
inline ::awolmsg::MsgAgent* Msg::mutable_actor() {
  set_has_actor();
  if (actor_ == NULL) actor_ = new ::awolmsg::MsgAgent;
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.actor)
  return actor_;
}
inline ::awolmsg::MsgAgent* Msg::release_actor() {
  clear_has_actor();
  ::awolmsg::MsgAgent* temp = actor_;
  actor_ = NULL;
  return temp;
}
inline void Msg::set_allocated_actor(::awolmsg::MsgAgent* actor) {
  delete actor_;
  actor_ = actor;
  if (actor) {
    set_has_actor();
  } else {
    clear_has_actor();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.actor)
}

// repeated .awolmsg.Msg.MsgData data = 3;
inline int Msg::data_size() const {
  return data_.size();
}
inline void Msg::clear_data() {
  data_.Clear();
}
inline const ::awolmsg::Msg_MsgData& Msg::data(int index) const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.data)
  return data_.Get(index);
}
inline ::awolmsg::Msg_MsgData* Msg::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.data)
  return data_.Mutable(index);
}
inline ::awolmsg::Msg_MsgData* Msg::add_data() {
  // @@protoc_insertion_point(field_add:awolmsg.Msg.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::awolmsg::Msg_MsgData >&
Msg::data() const {
  // @@protoc_insertion_point(field_list:awolmsg.Msg.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::awolmsg::Msg_MsgData >*
Msg::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:awolmsg.Msg.data)
  return &data_;
}

// optional .awolmsg.MsgFlag flag = 4;
inline bool Msg::has_flag() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Msg::set_has_flag() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Msg::clear_has_flag() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Msg::clear_flag() {
  if (flag_ != NULL) flag_->::awolmsg::MsgFlag::Clear();
  clear_has_flag();
}
inline const ::awolmsg::MsgFlag& Msg::flag() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.flag)
  return flag_ != NULL ? *flag_ : *default_instance_->flag_;
}
inline ::awolmsg::MsgFlag* Msg::mutable_flag() {
  set_has_flag();
  if (flag_ == NULL) flag_ = new ::awolmsg::MsgFlag;
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.flag)
  return flag_;
}
inline ::awolmsg::MsgFlag* Msg::release_flag() {
  clear_has_flag();
  ::awolmsg::MsgFlag* temp = flag_;
  flag_ = NULL;
  return temp;
}
inline void Msg::set_allocated_flag(::awolmsg::MsgFlag* flag) {
  delete flag_;
  flag_ = flag;
  if (flag) {
    set_has_flag();
  } else {
    clear_has_flag();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.flag)
}

// optional .awolmsg.MsgOP op = 5;
inline bool Msg::has_op() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Msg::set_has_op() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Msg::clear_has_op() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Msg::clear_op() {
  op_ = 1;
  clear_has_op();
}
inline ::awolmsg::MsgOP Msg::op() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.op)
  return static_cast< ::awolmsg::MsgOP >(op_);
}
inline void Msg::set_op(::awolmsg::MsgOP value) {
  assert(::awolmsg::MsgOP_IsValid(value));
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.Msg.op)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace awolmsg

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::awolmsg::MaxMsgTypeConstValue> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolmsg::MaxMsgTypeConstValue>() {
  return ::awolmsg::MaxMsgTypeConstValue_descriptor();
}
template <> struct is_proto_enum< ::awolmsg::MsgFlagOwnType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolmsg::MsgFlagOwnType>() {
  return ::awolmsg::MsgFlagOwnType_descriptor();
}
template <> struct is_proto_enum< ::awolmsg::MsgFalgStoreOptions> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolmsg::MsgFalgStoreOptions>() {
  return ::awolmsg::MsgFalgStoreOptions_descriptor();
}
template <> struct is_proto_enum< ::awolmsg::MsgFalgCpermOptions> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolmsg::MsgFalgCpermOptions>() {
  return ::awolmsg::MsgFalgCpermOptions_descriptor();
}
template <> struct is_proto_enum< ::awolmsg::MsgOP> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolmsg::MsgOP>() {
  return ::awolmsg::MsgOP_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_awolmsg_2eproto__INCLUDED
