// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awolapp.proto

#ifndef PROTOBUF_awolapp_2eproto__INCLUDED
#define PROTOBUF_awolapp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace awolapp {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_awolapp_2eproto();
void protobuf_AssignDesc_awolapp_2eproto();
void protobuf_ShutdownFile_awolapp_2eproto();

class MailAttachment;
class MailContent;
class MailOption;
class Mail;
class ChatSender;
class ChatContent;
class ChatMsg;
class Notice;

enum ActorType {
  ACTOR_TYPE_NONE = 0,
  ACTOR_TYPE_SERVER = 1,
  ACTOR_TYPE_PLAYER = 2
};
bool ActorType_IsValid(int value);
const ActorType ActorType_MIN = ACTOR_TYPE_NONE;
const ActorType ActorType_MAX = ACTOR_TYPE_PLAYER;
const int ActorType_ARRAYSIZE = ActorType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ActorType_descriptor();
inline const ::std::string& ActorType_Name(ActorType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ActorType_descriptor(), value);
}
inline bool ActorType_Parse(
    const ::std::string& name, ActorType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActorType>(
    ActorType_descriptor(), name, value);
}
enum MsgType {
  MSG_TYPE_NONE = 0,
  MSG_TYPE_MAIL = 1,
  MSG_TYPE_CHAT = 2,
  MSG_TYPE_NOTICE = 3
};
bool MsgType_IsValid(int value);
const MsgType MsgType_MIN = MSG_TYPE_NONE;
const MsgType MsgType_MAX = MSG_TYPE_NOTICE;
const int MsgType_ARRAYSIZE = MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgType_descriptor();
inline const ::std::string& MsgType_Name(MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgType_descriptor(), value);
}
inline bool MsgType_Parse(
    const ::std::string& name, MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgType>(
    MsgType_descriptor(), name, value);
}
enum MailState {
  MAIL_STATE_INIT = 0,
  MAIL_STATE_READ = 1,
  MAIL_STATE_FETCH = 2
};
bool MailState_IsValid(int value);
const MailState MailState_MIN = MAIL_STATE_INIT;
const MailState MailState_MAX = MAIL_STATE_FETCH;
const int MailState_ARRAYSIZE = MailState_MAX + 1;

const ::google::protobuf::EnumDescriptor* MailState_descriptor();
inline const ::std::string& MailState_Name(MailState value) {
  return ::google::protobuf::internal::NameOfEnum(
    MailState_descriptor(), value);
}
inline bool MailState_Parse(
    const ::std::string& name, MailState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MailState>(
    MailState_descriptor(), name, value);
}
// ===================================================================

class MailAttachment : public ::google::protobuf::Message {
 public:
  MailAttachment();
  virtual ~MailAttachment();

  MailAttachment(const MailAttachment& from);

  inline MailAttachment& operator=(const MailAttachment& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MailAttachment& default_instance();

  void Swap(MailAttachment* other);

  // implements Message ----------------------------------------------

  MailAttachment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailAttachment& from);
  void MergeFrom(const MailAttachment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:awolapp.MailAttachment)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static MailAttachment* default_instance_;
};
// -------------------------------------------------------------------

class MailContent : public ::google::protobuf::Message {
 public:
  MailContent();
  virtual ~MailContent();

  MailContent(const MailContent& from);

  inline MailContent& operator=(const MailContent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MailContent& default_instance();

  void Swap(MailContent* other);

  // implements Message ----------------------------------------------

  MailContent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailContent& from);
  void MergeFrom(const MailContent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:awolapp.MailContent)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static MailContent* default_instance_;
};
// -------------------------------------------------------------------

class MailOption : public ::google::protobuf::Message {
 public:
  MailOption();
  virtual ~MailOption();

  MailOption(const MailOption& from);

  inline MailOption& operator=(const MailOption& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MailOption& default_instance();

  void Swap(MailOption* other);

  // implements Message ----------------------------------------------

  MailOption* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailOption& from);
  void MergeFrom(const MailOption& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 expire_timestamp = 1;
  inline bool has_expire_timestamp() const;
  inline void clear_expire_timestamp();
  static const int kExpireTimestampFieldNumber = 1;
  inline ::google::protobuf::uint32 expire_timestamp() const;
  inline void set_expire_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolapp.MailOption)
 private:
  inline void set_has_expire_timestamp();
  inline void clear_has_expire_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 expire_timestamp_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static MailOption* default_instance_;
};
// -------------------------------------------------------------------

class Mail : public ::google::protobuf::Message {
 public:
  Mail();
  virtual ~Mail();

  Mail(const Mail& from);

  inline Mail& operator=(const Mail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Mail& default_instance();

  void Swap(Mail* other);

  // implements Message ----------------------------------------------

  Mail* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Mail& from);
  void MergeFrom(const Mail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline ::google::protobuf::uint64 from() const;
  inline void set_from(::google::protobuf::uint64 value);

  // optional string sender = 3;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 3;
  inline const ::std::string& sender() const;
  inline void set_sender(const ::std::string& value);
  inline void set_sender(const char* value);
  inline void set_sender(const char* value, size_t size);
  inline ::std::string* mutable_sender();
  inline ::std::string* release_sender();
  inline void set_allocated_sender(::std::string* sender);

  // optional string subject = 4;
  inline bool has_subject() const;
  inline void clear_subject();
  static const int kSubjectFieldNumber = 4;
  inline const ::std::string& subject() const;
  inline void set_subject(const ::std::string& value);
  inline void set_subject(const char* value);
  inline void set_subject(const char* value, size_t size);
  inline ::std::string* mutable_subject();
  inline ::std::string* release_subject();
  inline void set_allocated_subject(::std::string* subject);

  // optional .awolapp.MailContent content = 5;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 5;
  inline const ::awolapp::MailContent& content() const;
  inline ::awolapp::MailContent* mutable_content();
  inline ::awolapp::MailContent* release_content();
  inline void set_allocated_content(::awolapp::MailContent* content);

  // repeated .awolapp.MailAttachment attachements = 6;
  inline int attachements_size() const;
  inline void clear_attachements();
  static const int kAttachementsFieldNumber = 6;
  inline const ::awolapp::MailAttachment& attachements(int index) const;
  inline ::awolapp::MailAttachment* mutable_attachements(int index);
  inline ::awolapp::MailAttachment* add_attachements();
  inline const ::google::protobuf::RepeatedPtrField< ::awolapp::MailAttachment >&
      attachements() const;
  inline ::google::protobuf::RepeatedPtrField< ::awolapp::MailAttachment >*
      mutable_attachements();

  // optional .awolapp.MailOption option = 7;
  inline bool has_option() const;
  inline void clear_option();
  static const int kOptionFieldNumber = 7;
  inline const ::awolapp::MailOption& option() const;
  inline ::awolapp::MailOption* mutable_option();
  inline ::awolapp::MailOption* release_option();
  inline void set_allocated_option(::awolapp::MailOption* option);

  // optional .awolapp.MailState state = 8;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 8;
  inline ::awolapp::MailState state() const;
  inline void set_state(::awolapp::MailState value);

  // @@protoc_insertion_point(class_scope:awolapp.Mail)
 private:
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_subject();
  inline void clear_has_subject();
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_option();
  inline void clear_has_option();
  inline void set_has_state();
  inline void clear_has_state();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 from_;
  ::std::string* sender_;
  ::std::string* subject_;
  ::awolapp::MailContent* content_;
  ::google::protobuf::RepeatedPtrField< ::awolapp::MailAttachment > attachements_;
  ::awolapp::MailOption* option_;
  int state_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static Mail* default_instance_;
};
// -------------------------------------------------------------------

class ChatSender : public ::google::protobuf::Message {
 public:
  ChatSender();
  virtual ~ChatSender();

  ChatSender(const ChatSender& from);

  inline ChatSender& operator=(const ChatSender& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatSender& default_instance();

  void Swap(ChatSender* other);

  // implements Message ----------------------------------------------

  ChatSender* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatSender& from);
  void MergeFrom(const ChatSender& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:awolapp.ChatSender)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::std::string* name_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static ChatSender* default_instance_;
};
// -------------------------------------------------------------------

class ChatContent : public ::google::protobuf::Message {
 public:
  ChatContent();
  virtual ~ChatContent();

  ChatContent(const ChatContent& from);

  inline ChatContent& operator=(const ChatContent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatContent& default_instance();

  void Swap(ChatContent* other);

  // implements Message ----------------------------------------------

  ChatContent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatContent& from);
  void MergeFrom(const ChatContent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:awolapp.ChatContent)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static ChatContent* default_instance_;
};
// -------------------------------------------------------------------

class ChatMsg : public ::google::protobuf::Message {
 public:
  ChatMsg();
  virtual ~ChatMsg();

  ChatMsg(const ChatMsg& from);

  inline ChatMsg& operator=(const ChatMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMsg& default_instance();

  void Swap(ChatMsg* other);

  // implements Message ----------------------------------------------

  ChatMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMsg& from);
  void MergeFrom(const ChatMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .awolapp.ChatSender sender = 1;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 1;
  inline const ::awolapp::ChatSender& sender() const;
  inline ::awolapp::ChatSender* mutable_sender();
  inline ::awolapp::ChatSender* release_sender();
  inline void set_allocated_sender(::awolapp::ChatSender* sender);

  // optional .awolapp.ChatContent content = 2;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 2;
  inline const ::awolapp::ChatContent& content() const;
  inline ::awolapp::ChatContent* mutable_content();
  inline ::awolapp::ChatContent* release_content();
  inline void set_allocated_content(::awolapp::ChatContent* content);

  // optional uint32 timestamp = 3;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  inline ::google::protobuf::uint32 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolapp.ChatMsg)
 private:
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::awolapp::ChatSender* sender_;
  ::awolapp::ChatContent* content_;
  ::google::protobuf::uint32 timestamp_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static ChatMsg* default_instance_;
};
// -------------------------------------------------------------------

class Notice : public ::google::protobuf::Message {
 public:
  Notice();
  virtual ~Notice();

  Notice(const Notice& from);

  inline Notice& operator=(const Notice& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Notice& default_instance();

  void Swap(Notice* other);

  // implements Message ----------------------------------------------

  Notice* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Notice& from);
  void MergeFrom(const Notice& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:awolapp.Notice)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolapp_2eproto();
  friend void protobuf_AssignDesc_awolapp_2eproto();
  friend void protobuf_ShutdownFile_awolapp_2eproto();

  void InitAsDefaultInstance();
  static Notice* default_instance_;
};
// ===================================================================


// ===================================================================

// MailAttachment

// optional int32 type = 1;
inline bool MailAttachment::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailAttachment::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailAttachment::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailAttachment::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 MailAttachment::type() const {
  // @@protoc_insertion_point(field_get:awolapp.MailAttachment.type)
  return type_;
}
inline void MailAttachment::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolapp.MailAttachment.type)
}

// optional bytes data = 2;
inline bool MailAttachment::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailAttachment::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailAttachment::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailAttachment::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& MailAttachment::data() const {
  // @@protoc_insertion_point(field_get:awolapp.MailAttachment.data)
  return *data_;
}
inline void MailAttachment::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.MailAttachment.data)
}
inline void MailAttachment::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.MailAttachment.data)
}
inline void MailAttachment::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.MailAttachment.data)
}
inline ::std::string* MailAttachment::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.MailAttachment.data)
  return data_;
}
inline ::std::string* MailAttachment::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MailAttachment::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.MailAttachment.data)
}

// -------------------------------------------------------------------

// MailContent

// optional int32 type = 1;
inline bool MailContent::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailContent::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailContent::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailContent::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 MailContent::type() const {
  // @@protoc_insertion_point(field_get:awolapp.MailContent.type)
  return type_;
}
inline void MailContent::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolapp.MailContent.type)
}

// optional bytes data = 2;
inline bool MailContent::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailContent::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailContent::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailContent::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& MailContent::data() const {
  // @@protoc_insertion_point(field_get:awolapp.MailContent.data)
  return *data_;
}
inline void MailContent::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.MailContent.data)
}
inline void MailContent::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.MailContent.data)
}
inline void MailContent::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.MailContent.data)
}
inline ::std::string* MailContent::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.MailContent.data)
  return data_;
}
inline ::std::string* MailContent::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MailContent::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.MailContent.data)
}

// -------------------------------------------------------------------

// MailOption

// optional uint32 expire_timestamp = 1;
inline bool MailOption::has_expire_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailOption::set_has_expire_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailOption::clear_has_expire_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailOption::clear_expire_timestamp() {
  expire_timestamp_ = 0u;
  clear_has_expire_timestamp();
}
inline ::google::protobuf::uint32 MailOption::expire_timestamp() const {
  // @@protoc_insertion_point(field_get:awolapp.MailOption.expire_timestamp)
  return expire_timestamp_;
}
inline void MailOption::set_expire_timestamp(::google::protobuf::uint32 value) {
  set_has_expire_timestamp();
  expire_timestamp_ = value;
  // @@protoc_insertion_point(field_set:awolapp.MailOption.expire_timestamp)
}

// -------------------------------------------------------------------

// Mail

// optional uint64 from = 2;
inline bool Mail::has_from() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Mail::set_has_from() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Mail::clear_has_from() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Mail::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
  clear_has_from();
}
inline ::google::protobuf::uint64 Mail::from() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.from)
  return from_;
}
inline void Mail::set_from(::google::protobuf::uint64 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:awolapp.Mail.from)
}

// optional string sender = 3;
inline bool Mail::has_sender() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Mail::set_has_sender() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Mail::clear_has_sender() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Mail::clear_sender() {
  if (sender_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_->clear();
  }
  clear_has_sender();
}
inline const ::std::string& Mail::sender() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.sender)
  return *sender_;
}
inline void Mail::set_sender(const ::std::string& value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.Mail.sender)
}
inline void Mail::set_sender(const char* value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.Mail.sender)
}
inline void Mail::set_sender(const char* value, size_t size) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_ = new ::std::string;
  }
  sender_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.Mail.sender)
}
inline ::std::string* Mail::mutable_sender() {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.Mail.sender)
  return sender_;
}
inline ::std::string* Mail::release_sender() {
  clear_has_sender();
  if (sender_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sender_;
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Mail::set_allocated_sender(::std::string* sender) {
  if (sender_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sender_;
  }
  if (sender) {
    set_has_sender();
    sender_ = sender;
  } else {
    clear_has_sender();
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.Mail.sender)
}

// optional string subject = 4;
inline bool Mail::has_subject() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Mail::set_has_subject() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Mail::clear_has_subject() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Mail::clear_subject() {
  if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_->clear();
  }
  clear_has_subject();
}
inline const ::std::string& Mail::subject() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.subject)
  return *subject_;
}
inline void Mail::set_subject(const ::std::string& value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.Mail.subject)
}
inline void Mail::set_subject(const char* value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.Mail.subject)
}
inline void Mail::set_subject(const char* value, size_t size) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  subject_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.Mail.subject)
}
inline ::std::string* Mail::mutable_subject() {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    subject_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.Mail.subject)
  return subject_;
}
inline ::std::string* Mail::release_subject() {
  clear_has_subject();
  if (subject_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = subject_;
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Mail::set_allocated_subject(::std::string* subject) {
  if (subject_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete subject_;
  }
  if (subject) {
    set_has_subject();
    subject_ = subject;
  } else {
    clear_has_subject();
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.Mail.subject)
}

// optional .awolapp.MailContent content = 5;
inline bool Mail::has_content() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Mail::set_has_content() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Mail::clear_has_content() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Mail::clear_content() {
  if (content_ != NULL) content_->::awolapp::MailContent::Clear();
  clear_has_content();
}
inline const ::awolapp::MailContent& Mail::content() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.content)
  return content_ != NULL ? *content_ : *default_instance_->content_;
}
inline ::awolapp::MailContent* Mail::mutable_content() {
  set_has_content();
  if (content_ == NULL) content_ = new ::awolapp::MailContent;
  // @@protoc_insertion_point(field_mutable:awolapp.Mail.content)
  return content_;
}
inline ::awolapp::MailContent* Mail::release_content() {
  clear_has_content();
  ::awolapp::MailContent* temp = content_;
  content_ = NULL;
  return temp;
}
inline void Mail::set_allocated_content(::awolapp::MailContent* content) {
  delete content_;
  content_ = content;
  if (content) {
    set_has_content();
  } else {
    clear_has_content();
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.Mail.content)
}

// repeated .awolapp.MailAttachment attachements = 6;
inline int Mail::attachements_size() const {
  return attachements_.size();
}
inline void Mail::clear_attachements() {
  attachements_.Clear();
}
inline const ::awolapp::MailAttachment& Mail::attachements(int index) const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.attachements)
  return attachements_.Get(index);
}
inline ::awolapp::MailAttachment* Mail::mutable_attachements(int index) {
  // @@protoc_insertion_point(field_mutable:awolapp.Mail.attachements)
  return attachements_.Mutable(index);
}
inline ::awolapp::MailAttachment* Mail::add_attachements() {
  // @@protoc_insertion_point(field_add:awolapp.Mail.attachements)
  return attachements_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::awolapp::MailAttachment >&
Mail::attachements() const {
  // @@protoc_insertion_point(field_list:awolapp.Mail.attachements)
  return attachements_;
}
inline ::google::protobuf::RepeatedPtrField< ::awolapp::MailAttachment >*
Mail::mutable_attachements() {
  // @@protoc_insertion_point(field_mutable_list:awolapp.Mail.attachements)
  return &attachements_;
}

// optional .awolapp.MailOption option = 7;
inline bool Mail::has_option() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Mail::set_has_option() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Mail::clear_has_option() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Mail::clear_option() {
  if (option_ != NULL) option_->::awolapp::MailOption::Clear();
  clear_has_option();
}
inline const ::awolapp::MailOption& Mail::option() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.option)
  return option_ != NULL ? *option_ : *default_instance_->option_;
}
inline ::awolapp::MailOption* Mail::mutable_option() {
  set_has_option();
  if (option_ == NULL) option_ = new ::awolapp::MailOption;
  // @@protoc_insertion_point(field_mutable:awolapp.Mail.option)
  return option_;
}
inline ::awolapp::MailOption* Mail::release_option() {
  clear_has_option();
  ::awolapp::MailOption* temp = option_;
  option_ = NULL;
  return temp;
}
inline void Mail::set_allocated_option(::awolapp::MailOption* option) {
  delete option_;
  option_ = option;
  if (option) {
    set_has_option();
  } else {
    clear_has_option();
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.Mail.option)
}

// optional .awolapp.MailState state = 8;
inline bool Mail::has_state() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Mail::set_has_state() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Mail::clear_has_state() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Mail::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::awolapp::MailState Mail::state() const {
  // @@protoc_insertion_point(field_get:awolapp.Mail.state)
  return static_cast< ::awolapp::MailState >(state_);
}
inline void Mail::set_state(::awolapp::MailState value) {
  assert(::awolapp::MailState_IsValid(value));
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:awolapp.Mail.state)
}

// -------------------------------------------------------------------

// ChatSender

// optional uint64 id = 1;
inline bool ChatSender::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatSender::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatSender::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatSender::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 ChatSender::id() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatSender.id)
  return id_;
}
inline void ChatSender::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:awolapp.ChatSender.id)
}

// optional string name = 2;
inline bool ChatSender::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatSender::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatSender::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatSender::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ChatSender::name() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatSender.name)
  return *name_;
}
inline void ChatSender::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.ChatSender.name)
}
inline void ChatSender::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.ChatSender.name)
}
inline void ChatSender::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.ChatSender.name)
}
inline ::std::string* ChatSender::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.ChatSender.name)
  return name_;
}
inline ::std::string* ChatSender::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ChatSender::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.ChatSender.name)
}

// -------------------------------------------------------------------

// ChatContent

// optional int32 type = 1;
inline bool ChatContent::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatContent::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatContent::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatContent::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 ChatContent::type() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatContent.type)
  return type_;
}
inline void ChatContent::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolapp.ChatContent.type)
}

// optional bytes data = 2;
inline bool ChatContent::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatContent::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatContent::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatContent::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& ChatContent::data() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatContent.data)
  return *data_;
}
inline void ChatContent::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.ChatContent.data)
}
inline void ChatContent::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.ChatContent.data)
}
inline void ChatContent::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.ChatContent.data)
}
inline ::std::string* ChatContent::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.ChatContent.data)
  return data_;
}
inline ::std::string* ChatContent::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ChatContent::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.ChatContent.data)
}

// -------------------------------------------------------------------

// ChatMsg

// required .awolapp.ChatSender sender = 1;
inline bool ChatMsg::has_sender() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMsg::set_has_sender() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMsg::clear_has_sender() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMsg::clear_sender() {
  if (sender_ != NULL) sender_->::awolapp::ChatSender::Clear();
  clear_has_sender();
}
inline const ::awolapp::ChatSender& ChatMsg::sender() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatMsg.sender)
  return sender_ != NULL ? *sender_ : *default_instance_->sender_;
}
inline ::awolapp::ChatSender* ChatMsg::mutable_sender() {
  set_has_sender();
  if (sender_ == NULL) sender_ = new ::awolapp::ChatSender;
  // @@protoc_insertion_point(field_mutable:awolapp.ChatMsg.sender)
  return sender_;
}
inline ::awolapp::ChatSender* ChatMsg::release_sender() {
  clear_has_sender();
  ::awolapp::ChatSender* temp = sender_;
  sender_ = NULL;
  return temp;
}
inline void ChatMsg::set_allocated_sender(::awolapp::ChatSender* sender) {
  delete sender_;
  sender_ = sender;
  if (sender) {
    set_has_sender();
  } else {
    clear_has_sender();
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.ChatMsg.sender)
}

// optional .awolapp.ChatContent content = 2;
inline bool ChatMsg::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMsg::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMsg::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMsg::clear_content() {
  if (content_ != NULL) content_->::awolapp::ChatContent::Clear();
  clear_has_content();
}
inline const ::awolapp::ChatContent& ChatMsg::content() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatMsg.content)
  return content_ != NULL ? *content_ : *default_instance_->content_;
}
inline ::awolapp::ChatContent* ChatMsg::mutable_content() {
  set_has_content();
  if (content_ == NULL) content_ = new ::awolapp::ChatContent;
  // @@protoc_insertion_point(field_mutable:awolapp.ChatMsg.content)
  return content_;
}
inline ::awolapp::ChatContent* ChatMsg::release_content() {
  clear_has_content();
  ::awolapp::ChatContent* temp = content_;
  content_ = NULL;
  return temp;
}
inline void ChatMsg::set_allocated_content(::awolapp::ChatContent* content) {
  delete content_;
  content_ = content;
  if (content) {
    set_has_content();
  } else {
    clear_has_content();
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.ChatMsg.content)
}

// optional uint32 timestamp = 3;
inline bool ChatMsg::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatMsg::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatMsg::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatMsg::clear_timestamp() {
  timestamp_ = 0u;
  clear_has_timestamp();
}
inline ::google::protobuf::uint32 ChatMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:awolapp.ChatMsg.timestamp)
  return timestamp_;
}
inline void ChatMsg::set_timestamp(::google::protobuf::uint32 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:awolapp.ChatMsg.timestamp)
}

// -------------------------------------------------------------------

// Notice

// required int32 type = 1;
inline bool Notice::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Notice::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Notice::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Notice::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Notice::type() const {
  // @@protoc_insertion_point(field_get:awolapp.Notice.type)
  return type_;
}
inline void Notice::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolapp.Notice.type)
}

// optional bytes data = 2;
inline bool Notice::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Notice::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Notice::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Notice::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Notice::data() const {
  // @@protoc_insertion_point(field_get:awolapp.Notice.data)
  return *data_;
}
inline void Notice::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolapp.Notice.data)
}
inline void Notice::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolapp.Notice.data)
}
inline void Notice::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolapp.Notice.data)
}
inline ::std::string* Notice::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolapp.Notice.data)
  return data_;
}
inline ::std::string* Notice::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Notice::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolapp.Notice.data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace awolapp

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::awolapp::ActorType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolapp::ActorType>() {
  return ::awolapp::ActorType_descriptor();
}
template <> struct is_proto_enum< ::awolapp::MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolapp::MsgType>() {
  return ::awolapp::MsgType_descriptor();
}
template <> struct is_proto_enum< ::awolapp::MailState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::awolapp::MailState>() {
  return ::awolapp::MailState_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_awolapp_2eproto__INCLUDED
