// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awolmsg.proto

#ifndef PROTOBUF_awolmsg_2eproto__INCLUDED
#define PROTOBUF_awolmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace awolmsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_awolmsg_2eproto();
void protobuf_AssignDesc_awolmsg_2eproto();
void protobuf_ShutdownFile_awolmsg_2eproto();

class MsgExt;
class Msg;

// ===================================================================

class MsgExt : public ::google::protobuf::Message {
 public:
  MsgExt();
  virtual ~MsgExt();

  MsgExt(const MsgExt& from);

  inline MsgExt& operator=(const MsgExt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgExt& default_instance();

  void Swap(MsgExt* other);

  // implements Message ----------------------------------------------

  MsgExt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgExt& from);
  void MergeFrom(const MsgExt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);

  // optional uint32 ttl = 2;
  inline bool has_ttl() const;
  inline void clear_ttl();
  static const int kTtlFieldNumber = 2;
  inline ::google::protobuf::uint32 ttl() const;
  inline void set_ttl(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:awolmsg.MsgExt)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_ttl();
  inline void clear_has_ttl();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 time_;
  ::google::protobuf::uint32 ttl_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static MsgExt* default_instance_;
};
// -------------------------------------------------------------------

class Msg : public ::google::protobuf::Message {
 public:
  Msg();
  virtual ~Msg();

  Msg(const Msg& from);

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg& default_instance();

  void Swap(Msg* other);

  // implements Message ----------------------------------------------

  Msg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg& from);
  void MergeFrom(const Msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional int32 type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional .awolmsg.MsgExt ext = 4;
  inline bool has_ext() const;
  inline void clear_ext();
  static const int kExtFieldNumber = 4;
  inline const ::awolmsg::MsgExt& ext() const;
  inline ::awolmsg::MsgExt* mutable_ext();
  inline ::awolmsg::MsgExt* release_ext();
  inline void set_allocated_ext(::awolmsg::MsgExt* ext);

  // @@protoc_insertion_point(class_scope:awolmsg.Msg)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_ext();
  inline void clear_has_ext();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::std::string* data_;
  ::awolmsg::MsgExt* ext_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_awolmsg_2eproto();
  friend void protobuf_AssignDesc_awolmsg_2eproto();
  friend void protobuf_ShutdownFile_awolmsg_2eproto();

  void InitAsDefaultInstance();
  static Msg* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgExt

// optional uint32 time = 1;
inline bool MsgExt::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgExt::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgExt::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgExt::clear_time() {
  time_ = 0u;
  clear_has_time();
}
inline ::google::protobuf::uint32 MsgExt::time() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.time)
  return time_;
}
inline void MsgExt::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgExt.time)
}

// optional uint32 ttl = 2;
inline bool MsgExt::has_ttl() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgExt::set_has_ttl() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgExt::clear_has_ttl() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgExt::clear_ttl() {
  ttl_ = 0u;
  clear_has_ttl();
}
inline ::google::protobuf::uint32 MsgExt::ttl() const {
  // @@protoc_insertion_point(field_get:awolmsg.MsgExt.ttl)
  return ttl_;
}
inline void MsgExt::set_ttl(::google::protobuf::uint32 value) {
  set_has_ttl();
  ttl_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.MsgExt.ttl)
}

// -------------------------------------------------------------------

// Msg

// required uint64 id = 1;
inline bool Msg::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Msg::id() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.id)
  return id_;
}
inline void Msg::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.Msg.id)
}

// optional int32 type = 2;
inline bool Msg::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Msg::type() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.type)
  return type_;
}
inline void Msg::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:awolmsg.Msg.type)
}

// optional bytes data = 3;
inline bool Msg::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Msg::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Msg::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Msg::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Msg::data() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.data)
  return *data_;
}
inline void Msg::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:awolmsg.Msg.data)
}
inline void Msg::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:awolmsg.Msg.data)
}
inline void Msg::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:awolmsg.Msg.data)
}
inline ::std::string* Msg::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.data)
  return data_;
}
inline ::std::string* Msg::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Msg::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.data)
}

// optional .awolmsg.MsgExt ext = 4;
inline bool Msg::has_ext() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Msg::set_has_ext() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Msg::clear_has_ext() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Msg::clear_ext() {
  if (ext_ != NULL) ext_->::awolmsg::MsgExt::Clear();
  clear_has_ext();
}
inline const ::awolmsg::MsgExt& Msg::ext() const {
  // @@protoc_insertion_point(field_get:awolmsg.Msg.ext)
  return ext_ != NULL ? *ext_ : *default_instance_->ext_;
}
inline ::awolmsg::MsgExt* Msg::mutable_ext() {
  set_has_ext();
  if (ext_ == NULL) ext_ = new ::awolmsg::MsgExt;
  // @@protoc_insertion_point(field_mutable:awolmsg.Msg.ext)
  return ext_;
}
inline ::awolmsg::MsgExt* Msg::release_ext() {
  clear_has_ext();
  ::awolmsg::MsgExt* temp = ext_;
  ext_ = NULL;
  return temp;
}
inline void Msg::set_allocated_ext(::awolmsg::MsgExt* ext) {
  delete ext_;
  ext_ = ext;
  if (ext) {
    set_has_ext();
  } else {
    clear_has_ext();
  }
  // @@protoc_insertion_point(field_set_allocated:awolmsg.Msg.ext)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace awolmsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_awolmsg_2eproto__INCLUDED
